# https://archive.apache.org/dist/spark/spark-2.4.3/spark-2.4.3-bin-hadoop2.7.tgz
steps:
  - name: gcr.io/cloud-builders/wget
    entrypoint: bash
    args:
      - -c
      - |
        wget -q -O dist.tgz $$DIST_URL
        wget https://storage.googleapis.com/hadoop-lib/gcs/gcs-connector-latest-hadoop2.jar 
    env:
      - 'DIST_URL=${_DIST_URL}'     

  - name: debian
    entrypoint: bash
    args: 
      - -c
      - |
        mkdir dist
        tar xzf dist.tgz -C dist --strip-components=1
        mv gcs-connector-latest-hadoop2.jar dist/jars

  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        cd dist && ./bin/docker-image-tool.sh -r gcr.io/$PROJECT_ID -t $$IMAGE_TAG build    
    env:
      - 'IMAGE_TAG=${_IMAGE_TAG}'         

tags: ['cloud-build-spark']
images: ['gcr.io/$PROJECT_ID/spark']

